services:
  frontend:
    image: img-frontend:latest
    container_name: frontend
    ports:
      - "4200:4200"
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
  backend:
    image: img-backend:latest
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
